package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dc-tec/openbao-observability/internal/contracts"
	"github.com/prometheus/prometheus/promql/parser"
	"gopkg.in/yaml.v3"
)

type GenerateOptions struct {
	ContractPath string
	OutputPath   string
	SourcePrefix string
}

type prometheusRule struct {
	APIVersion string             `yaml:"apiVersion"`
	Kind       string             `yaml:"kind"`
	Metadata   map[string]string  `yaml:"metadata"`
	Spec       prometheusRuleSpec `yaml:"spec"`
}

type prometheusRuleSpec struct {
	Groups []prometheusRuleGroup `yaml:"groups"`
}

type prometheusRuleGroup struct {
	Name  string          `yaml:"name"`
	Rules []recordingRule `yaml:"rules"`
}

type recordingRule struct {
	Record string            `yaml:"record"`
	Expr   string            `yaml:"expr"`
	Labels map[string]string `yaml:"labels,omitempty"`
}

func GeneratePrometheusRules(opts GenerateOptions) error {
	opts = opts.withDefaults()

	contract, err := contracts.LoadMetricContract(opts.ContractPath)
	if err != nil {
		return err
	}

	sourcePrefix := opts.SourcePrefix
	if sourcePrefix == "" {
		sourcePrefix = contract.MetricPrefixes.Default
	}

	document := buildPrometheusRule(*contract, sourcePrefix)
	if err := validatePromQL(document); err != nil {
		return err
	}

	content, err := yaml.Marshal(document)
	if err != nil {
		return fmt.Errorf("marshal PrometheusRule: %w", err)
	}

	header := []byte("# Code generated by openbao-observability; DO NOT EDIT.\n")
	content = append(header, content...)

	if err := os.MkdirAll(filepath.Dir(opts.OutputPath), 0o755); err != nil {
		return fmt.Errorf("create output directory for %s: %w", opts.OutputPath, err)
	}
	if err := os.WriteFile(opts.OutputPath, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", opts.OutputPath, err)
	}

	fmt.Printf("generated PrometheusRule at %s\n", opts.OutputPath)
	return nil
}

func (o GenerateOptions) withDefaults() GenerateOptions {
	if o.ContractPath == "" {
		o.ContractPath = filepath.Join("contracts", "metrics", "openbao-core.yaml")
	}
	if o.OutputPath == "" {
		o.OutputPath = filepath.Join("generated", "prometheusrules", "openbao-recording-rules.yaml")
	}
	return o
}

func buildPrometheusRule(contract contracts.MetricContract, sourcePrefix string) prometheusRule {
	recordPrefix := contract.Normalization.RecordingRulePrefix

	return prometheusRule{
		APIVersion: "monitoring.coreos.com/v1",
		Kind:       "PrometheusRule",
		Metadata: map[string]string{
			"name": "openbao-recording-rules",
		},
		Spec: prometheusRuleSpec{
			Groups: []prometheusRuleGroup{
				{
					Name: "openbao.recording",
					Rules: []recordingRule{
						{
							Record: recordPrefix + ":core_active:sum",
							Expr:   "sum(" + metricName(sourcePrefix, "core_active") + ")",
							Labels: ruleLabels(sourcePrefix),
						},
						{
							Record: recordPrefix + ":core_unsealed:sum",
							Expr:   `sum(` + metricName(sourcePrefix, "core_unsealed") + `{cluster!=""})`,
							Labels: ruleLabels(sourcePrefix),
						},
						{
							Record: recordPrefix + ":audit_log_request_failure:increase5m",
							Expr:   "sum(increase(" + metricName(sourcePrefix, "audit_log_request_failure") + "[5m]))",
							Labels: ruleLabels(sourcePrefix),
						},
						{
							Record: recordPrefix + ":audit_log_response_failure:increase5m",
							Expr:   "sum(increase(" + metricName(sourcePrefix, "audit_log_response_failure") + "[5m]))",
							Labels: ruleLabels(sourcePrefix),
						},
						{
							Record: recordPrefix + ":expire_num_leases:max",
							Expr:   "max(" + metricName(sourcePrefix, "expire_num_leases") + ")",
							Labels: ruleLabels(sourcePrefix),
						},
						{
							Record: recordPrefix + ":runtime_num_goroutines:max",
							Expr:   "max(" + metricName(sourcePrefix, "runtime_num_goroutines") + ")",
							Labels: ruleLabels(sourcePrefix),
						},
					},
				},
			},
		},
	}
}

func metricName(prefix, id string) string {
	return prefix + "_" + strings.TrimPrefix(id, "_")
}

func validatePromQL(document prometheusRule) error {
	promQLParser := parser.NewParser(parser.Options{})
	for _, group := range document.Spec.Groups {
		for _, rule := range group.Rules {
			if _, err := promQLParser.ParseExpr(rule.Expr); err != nil {
				return fmt.Errorf("parse PromQL for recording rule %s: %w", rule.Record, err)
			}
		}
	}
	return nil
}

func ruleLabels(sourcePrefix string) map[string]string {
	return map[string]string{
		"source_prefix": sourcePrefix,
	}
}
