package rules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dc-tec/openbao-observability/internal/contracts"
)

func TestGeneratePrometheusRules(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "contract.yaml")
	outputPath := filepath.Join(dir, "rules.yaml")
	ruleFilePath := filepath.Join(dir, "prometheus-rules.yaml")

	if err := os.WriteFile(contractPath, []byte(ruleContract()), 0o644); err != nil {
		t.Fatalf("write contract: %v", err)
	}

	err := GeneratePrometheusRules(GenerateOptions{
		ContractPath: contractPath,
		OutputPath:   outputPath,
		RuleFilePath: ruleFilePath,
		SourcePrefix: "openbao",
	})
	if err != nil {
		t.Fatalf("GeneratePrometheusRules returned error: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	text := string(content)

	required := []string{
		"# Code generated by openbao-observability; DO NOT EDIT.",
		"record: openbao:core_active:sum",
		"expr: sum(openbao_core_active)",
		"expr: sum(openbao_core_unsealed{cluster!=\"\"})",
		"record: openbao:core_handle_request:rate5m",
		"expr: sum(rate(openbao_core_handle_request_count[5m]))",
		"record: openbao:core_handle_login_request:avg5m",
		"expr: sum(rate(openbao_core_handle_login_request_sum[5m])) / " +
			"clamp_min(sum(rate(openbao_core_handle_login_request_count[5m])), 0.001)",
		"record: openbao:core_check_token:avg5m",
		"expr: sum(rate(openbao_core_check_token_sum[5m])) / clamp_min(sum(rate(openbao_core_check_token_count[5m])), 0.001)",
		"record: openbao:core_in_flight_requests:max",
		"expr: max(openbao_core_in_flight_requests)",
		"record: openbao:core_mount_table_num_entries:max",
		"expr: max by (local, type) (openbao_core_mount_table_num_entries)",
		"record: openbao:raft_peers:max",
		"expr: max(openbao_raft_peers) or count(count by (peer_id) (openbao_raft_storage_stats_commit_index))",
		"record: openbao:autopilot_node_healthy:min",
		"expr: min by (node_id) (openbao_autopilot_node_healthy)",
		"record: openbao:raft_storage_apply_gap:max",
		"expr: clamp_min(max by (instance, peer_id) (openbao_raft_storage_stats_commit_index - " +
			"openbao_raft_storage_stats_applied_index), 0)",
		"record: openbao:audit_log_request:avg5m",
		"expr: sum(rate(openbao_audit_log_request_sum[5m])) / " +
			"clamp_min(sum(rate(openbao_audit_log_request_count[5m])), 0.001)",
		"record: openbao:expire_num_irrevocable_leases:max",
		"expr: max(openbao_expire_num_irrevocable_leases)",
		"record: openbao:token_count:max30m",
		"expr: max(max_over_time(openbao_token_count[30m]))",
		"record: openbao:token_creation_by_auth:increase15m",
		"expr: sum by (auth_method) (increase(openbao_token_creation[15m]))",
		"record: openbao:token_creation_by_namespace:increase15m",
		"expr: sum by (namespace) (increase(openbao_token_creation[15m]))",
		"record: openbao:token_creation_by_auth_namespace:increase15m",
		"expr: sum by (namespace, auth_method) (increase(openbao_token_creation[15m]))",
		"record: openbao:token_lookup:avg5m",
		"expr: sum(rate(openbao_token_lookup_sum[5m])) / clamp_min(sum(rate(openbao_token_lookup_count[5m])), 0.001)",
		"record: openbao:runtime_heap_objects:max",
		"expr: max(openbao_runtime_heap_objects)",
		"record: openbao:barrier_get:avg5m",
		"expr: sum(rate(openbao_barrier_get_sum[5m])) / clamp_min(sum(rate(openbao_barrier_get_count[5m])), 0.001)",
		"record: openbao:cache_hit_ratio:ratio5m",
		"expr: sum(rate(openbao_cache_hit[5m])) / " +
			"clamp_min(sum(rate(openbao_cache_hit[5m])) + sum(rate(openbao_cache_miss[5m])), 0.001)",
		"record: openbao:secret_lease_creation_by_engine:increase15m",
		"expr: sum by (secret_engine) (increase(openbao_secret_lease_creation[15m]))",
		"record: openbao:secret_lease_creation_by_engine_namespace:increase15m",
		"expr: sum by (namespace, secret_engine) (increase(openbao_secret_lease_creation[15m]))",
		"record: openbao:pki_issue:avg5m",
		"expr: sum(rate(openbao_pki_issue_sum[5m])) / clamp_min(sum(rate(openbao_pki_issue_count[5m])), 0.001)",
		"record: openbao:pki_issue_failure:increase15m",
		"expr: sum(increase(openbao_pki_issue_failure[15m]))",
		"record: openbao:database_new_user:rate5m",
		"expr: sum(rate(openbao_database_NewUser_count[5m]))",
		"record: openbao:database_new_user_error:increase15m",
		"expr: sum(increase(openbao_database_NewUser_error[15m]))",
		"source_prefix: openbao",
	}
	for _, fragment := range required {
		if !strings.Contains(text, fragment) {
			t.Fatalf("generated rules missing %q:\n%s", fragment, text)
		}
	}

	ruleFileContent, err := os.ReadFile(ruleFilePath)
	if err != nil {
		t.Fatalf("read Prometheus rule file: %v", err)
	}
	ruleFileText := string(ruleFileContent)
	for _, fragment := range []string{
		"groups:",
		"name: openbao.recording",
		"record: openbao:core_active:sum",
	} {
		if !strings.Contains(ruleFileText, fragment) {
			t.Fatalf("generated Prometheus rule file missing %q:\n%s", fragment, ruleFileText)
		}
	}
	if strings.Contains(ruleFileText, "kind: PrometheusRule") {
		t.Fatalf("native Prometheus rule file contains PrometheusRule wrapper:\n%s", ruleFileText)
	}
}

func TestValidatePromQLRejectsInvalidExpression(t *testing.T) {
	document := prometheusRule{
		Spec: prometheusRuleSpec{
			Groups: []prometheusRuleGroup{
				{
					Name: "test",
					Rules: []prometheusRuleItem{
						{Record: "openbao:invalid", Expr: "sum("},
					},
				},
			},
		},
	}

	err := validatePromQL(document)
	if err == nil {
		t.Fatal("expected invalid PromQL to fail")
	}
	if !strings.Contains(err.Error(), "openbao:invalid") {
		t.Fatalf("error does not include rule name: %v", err)
	}
}

func TestGenerateAlertRules(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "alerts.yaml")
	prometheusOutputPath := filepath.Join(dir, "prometheus-alerts.yaml")
	prometheusRuleFilePath := filepath.Join(dir, "prometheus-alert-rules.yaml")
	lokiOutputPath := filepath.Join(dir, "loki-alerts.yaml")

	if err := os.WriteFile(contractPath, []byte(alertContract()), 0o644); err != nil {
		t.Fatalf("write alert contract: %v", err)
	}

	err := GenerateAlertRules(GenerateAlertOptions{
		ContractPath:           contractPath,
		PrometheusOutputPath:   prometheusOutputPath,
		PrometheusRuleFilePath: prometheusRuleFilePath,
		LokiOutputPath:         lokiOutputPath,
		SourcePrefix:           "openbao",
	})
	if err != nil {
		t.Fatalf("GenerateAlertRules returned error: %v", err)
	}

	prometheusContent, err := os.ReadFile(prometheusOutputPath)
	if err != nil {
		t.Fatalf("read Prometheus output: %v", err)
	}
	prometheusText := string(prometheusContent)
	for _, fragment := range []string{
		"kind: PrometheusRule",
		"alert: OpenBaoNoActiveNode",
		"expr: sum(openbao_core_active) == 0",
		"alert: OpenBaoMultipleActiveNodes",
		"expr: sum(openbao_core_active) > 1",
		"alert: OpenBaoAutopilotFailureToleranceLost",
		"expr: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1",
		"component: raft",
		"alert: OpenBaoAuditResponseFailures",
		"expr: sum(increase(openbao_audit_log_response_failure[5m])) > 0",
		"runbook_url: docs/runbooks/no-active-openbao-leader.md",
	} {
		if !strings.Contains(prometheusText, fragment) {
			t.Fatalf("Prometheus alerts missing %q:\n%s", fragment, prometheusText)
		}
	}

	prometheusRuleFileContent, err := os.ReadFile(prometheusRuleFilePath)
	if err != nil {
		t.Fatalf("read Prometheus alert rule file: %v", err)
	}
	prometheusRuleFileText := string(prometheusRuleFileContent)
	for _, fragment := range []string{
		"groups:",
		"name: openbao.alerts",
		"alert: OpenBaoNoActiveNode",
		"expr: sum(openbao_core_active) == 0",
		"alert: OpenBaoMultipleActiveNodes",
		"expr: sum(openbao_core_active) > 1",
		"alert: OpenBaoAutopilotFailureToleranceLost",
		"expr: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1",
		"alert: OpenBaoAuditResponseFailures",
		"expr: sum(increase(openbao_audit_log_response_failure[5m])) > 0",
	} {
		if !strings.Contains(prometheusRuleFileText, fragment) {
			t.Fatalf("Prometheus alert rule file missing %q:\n%s", fragment, prometheusRuleFileText)
		}
	}
	if strings.Contains(prometheusRuleFileText, "kind: PrometheusRule") {
		t.Fatalf("native Prometheus alert rule file contains PrometheusRule wrapper:\n%s", prometheusRuleFileText)
	}

	lokiContent, err := os.ReadFile(lokiOutputPath)
	if err != nil {
		t.Fatalf("read Loki output: %v", err)
	}
	lokiText := string(lokiContent)
	for _, fragment := range []string{
		"kind: LokiAlertRules",
		"alert: OpenBaoAuditCanaryMissing",
		"expr: absent_over_time({log_stream=\"openbao.audit\"} | json request_path=\"request.path\" | " +
			"request_path=\"secret/data/observability/audit-canary\" [15m])",
	} {
		if !strings.Contains(lokiText, fragment) {
			t.Fatalf("Loki alerts missing %q:\n%s", fragment, lokiText)
		}
	}
}

func TestBuildPrometheusRuleUsesDefaultRecordPrefix(t *testing.T) {
	document := buildPrometheusRule(contracts.MetricContract{
		Normalization: contracts.Normalization{RecordingRulePrefix: "openbao"},
	}, "vault")

	if got := document.Spec.Groups[0].Rules[0].Record; got != "openbao:core_active:sum" {
		t.Fatalf("record name = %q", got)
	}
}

func ruleContract() string {
	return `version: v0.1
status: draft
openbaoVersion: "2.5.4"
metricPrefixes:
  supported:
    - vault
    - openbao
  default: vault
normalization:
  recordingRulePrefix: openbao
fixtures:
  required: []
metrics:
  - id: core_active
    prometheusName: ${p}_core_active
    required: true
`
}

func alertContract() string {
	return `version: v0.1
status: draft
metricPrefixVariable: ${p}
sourcePrefix: vault
alerts:
  - id: OpenBaoNoActiveNode
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: sum(${p}_core_active) == 0
    summary: OpenBao has no active node
    description: No active OpenBao node is visible to Prometheus.
    runbook: docs/runbooks/no-active-openbao-leader.md
  - id: OpenBaoMultipleActiveNodes
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: sum(${p}_core_active) > 1
    summary: OpenBao has multiple active nodes
    description: More than one active OpenBao node is visible to Prometheus.
    runbook: docs/runbooks/multiple-active-nodes.md
  - id: OpenBaoAutopilotFailureToleranceLost
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1
    summary: OpenBao Autopilot has no tolerated voter failure
    description: >-
      OpenBao Autopilot reports that the Raft cluster cannot lose a voter while maintaining the configured HA baseline.
    runbook: docs/runbooks/raft-autopilot-health.md
    labels:
      component: raft
      subsystem: autopilot
  - id: OpenBaoAuditResponseFailures
    type: prometheus
    severity: critical
    signal: metrics
    for: 0m
    expression: sum(increase(${p}_audit_log_response_failure[5m])) > 0
    summary: OpenBao audit response logging failed
    description: OpenBao reported at least one audit response logging failure.
    runbook: docs/runbooks/audit-request-response-failures.md
  - id: OpenBaoAuditCanaryMissing
    type: loki
    severity: critical
    signal: loki
    for: 15m
    expression: >-
      absent_over_time({log_stream="openbao.audit"} | json request_path="request.path" |
      request_path="secret/data/observability/audit-canary" [15m])
    summary: OpenBao audit canary is missing
    description: Loki has not received the expected OpenBao audit canary request for the alert window.
    runbook: docs/runbooks/audit-canary-missing.md
`
}
