package rules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dc-tec/openbao-observability/internal/contracts"
	promlabels "github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/promql/parser"
)

func TestGeneratePrometheusRules(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "contract.yaml")
	outputPath := filepath.Join(dir, "rules.yaml")
	ruleFilePath := filepath.Join(dir, "prometheus-rules.yaml")

	if err := os.WriteFile(contractPath, []byte(ruleContract()), 0o644); err != nil {
		t.Fatalf("write contract: %v", err)
	}

	err := GeneratePrometheusRules(GenerateOptions{
		ContractPath: contractPath,
		OutputPath:   outputPath,
		RuleFilePath: ruleFilePath,
		SourcePrefix: "openbao",
	})
	if err != nil {
		t.Fatalf("GeneratePrometheusRules returned error: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	text := string(content)

	cluster := clusterGrouping()
	target := targetGrouping()
	required := []string{
		"# Code generated by openbao-observability; DO NOT EDIT.",
		"record: openbao:core_active:sum",
		"expr: sum by (" + cluster + ") (openbao_core_active)",
		"record: openbao:core_unsealed:sum",
		"expr: sum by (" + cluster + ") (openbao_core_unsealed{cluster!=\"\"})",
		"record: openbao:core_unsealed:min",
		"expr: min by (" + target + ") (openbao_core_unsealed{cluster!=\"\"})",
		"record: openbao:core_handle_request:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_core_handle_request_count[5m]))",
		"record: openbao:core_handle_login_request:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_core_handle_login_request_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_core_handle_login_request_count[5m])), 0.001)",
		"record: openbao:core_check_token:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_core_check_token_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_core_check_token_count[5m])), 0.001)",
		"record: openbao:core_in_flight_requests:max",
		"expr: max by (" + target + ") (openbao_core_in_flight_requests)",
		"record: openbao:core_mount_table_num_entries:max",
		"expr: max by (" + clusterGrouping("local", "type") + ") (openbao_core_mount_table_num_entries)",
		"record: openbao:raft_peers:max",
		"expr: max by (" + cluster + ") (openbao_raft_peers) or " +
			"count by (" + cluster + ") (openbao_autopilot_node_healthy) or " +
			"count by (" + cluster + ") (count by (" + clusterGrouping("peer_id") + ") " +
			"(openbao_raft_storage_stats_commit_index))",
		"record: openbao:autopilot_node_healthy:min",
		"expr: min by (" + targetGrouping("node_id") + ") (openbao_autopilot_node_healthy)",
		"record: openbao:raft_storage_apply_gap:max",
		"expr: clamp_min(max by (" + targetGrouping("peer_id") + ") (openbao_raft_storage_stats_commit_index - " +
			"openbao_raft_storage_stats_applied_index), 0)",
		"record: openbao:audit_log_request:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_audit_log_request_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_audit_log_request_count[5m])), 0.001)",
		"record: openbao:expire_num_irrevocable_leases:max",
		"expr: max by (" + cluster + ") (openbao_expire_num_irrevocable_leases)",
		"record: openbao:token_count:max30m",
		"expr: max by (" + cluster + ") (max_over_time(openbao_token_count[30m]))",
		"record: openbao:token_creation_by_auth:increase15m",
		"expr: sum by (" + clusterGrouping("auth_method") + ") (increase(openbao_token_creation[15m]))",
		"record: openbao:token_creation_by_namespace:increase15m",
		"expr: sum by (" + cluster + ") (increase(openbao_token_creation[15m]))",
		"record: openbao:token_creation_by_auth_namespace:increase15m",
		"expr: sum by (" + clusterGrouping("auth_method") + ") (increase(openbao_token_creation[15m]))",
		"record: openbao:token_lookup:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_token_lookup_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_token_lookup_count[5m])), 0.001)",
		"record: openbao:runtime_heap_objects:max",
		"expr: max by (" + target + ") (openbao_runtime_heap_objects)",
		"record: openbao:barrier_get:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_barrier_get_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_barrier_get_count[5m])), 0.001)",
		"record: openbao:cache_hit_ratio:ratio5m",
		"expr: sum by (" + cluster + ") (rate(openbao_cache_hit[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_cache_hit[5m])) + " +
			"sum by (" + cluster + ") (rate(openbao_cache_miss[5m])), 0.001)",
		"record: openbao:secret_lease_creation_by_engine:increase15m",
		"expr: sum by (" + clusterGrouping("secret_engine") + ") (increase(openbao_secret_lease_creation[15m]))",
		"record: openbao:secret_lease_creation_by_engine_namespace:increase15m",
		"expr: sum by (" + clusterGrouping("secret_engine") + ") (increase(openbao_secret_lease_creation[15m]))",
		"record: openbao:secret_kv_count:max30m",
		"expr: sum by (" + cluster + ") (max by (" + clusterGrouping("mount_point") + ") " +
			"(max_over_time(openbao_secret_kv_count[30m])))",
		"record: openbao:secret_kv_count_by_namespace:max30m",
		"expr: sum by (" + cluster + ") (max by (" + clusterGrouping("mount_point") + ") " +
			"(max_over_time(openbao_secret_kv_count[30m])))",
		"record: openbao:route_create_kv_v1:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_create_kv_v1__count[5m]))",
		"record: openbao:route_read_kv_v1:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_read_kv_v1__sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_route_read_kv_v1__count[5m])), 0.001)",
		"record: openbao:route_delete_kv_v1:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_delete_kv_v1__count[5m]))",
		"record: openbao:route_create_kv_v2:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_create_secret__count[5m]))",
		"record: openbao:route_read_kv_v2:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_read_secret__sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_route_read_secret__count[5m])), 0.001)",
		"record: openbao:route_delete_kv_v2:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_route_delete_secret__count[5m]))",
		"record: openbao:pki_issue:avg5m",
		"expr: sum by (" + cluster + ") (rate(openbao_pki_issue_sum[5m])) / " +
			"clamp_min(sum by (" + cluster + ") (rate(openbao_pki_issue_count[5m])), 0.001)",
		"record: openbao:pki_issue_failure:increase15m",
		"expr: sum by (" + cluster + ") (increase(openbao_pki_issue_failure[15m]))",
		"record: openbao:database_new_user:rate5m",
		"expr: sum by (" + cluster + ") (rate(openbao_database_NewUser_count[5m]))",
		"record: openbao:database_new_user_error:increase15m",
		"expr: sum by (" + cluster + ") (increase(openbao_database_NewUser_error[15m]))",
		"source_prefix: openbao",
	}
	for _, fragment := range required {
		if !strings.Contains(text, fragment) {
			t.Fatalf("generated rules missing %q:\n%s", fragment, text)
		}
	}

	ruleFileContent, err := os.ReadFile(ruleFilePath)
	if err != nil {
		t.Fatalf("read Prometheus rule file: %v", err)
	}
	ruleFileText := string(ruleFileContent)
	for _, fragment := range []string{
		"groups:",
		"name: openbao.recording",
		"record: openbao:core_active:sum",
	} {
		if !strings.Contains(ruleFileText, fragment) {
			t.Fatalf("generated Prometheus rule file missing %q:\n%s", fragment, ruleFileText)
		}
	}
	if strings.Contains(ruleFileText, "kind: PrometheusRule") {
		t.Fatalf("native Prometheus rule file contains PrometheusRule wrapper:\n%s", ruleFileText)
	}
}

func TestGeneratePrometheusRulesAcceptsSupportedSourcePrefixes(t *testing.T) {
	for _, sourcePrefix := range []string{"vault", "openbao"} {
		t.Run(sourcePrefix, func(t *testing.T) {
			dir := t.TempDir()
			contractPath := filepath.Join(dir, "contract.yaml")
			outputPath := filepath.Join(dir, "rules.yaml")
			if err := os.WriteFile(contractPath, []byte(ruleContract()), 0o644); err != nil {
				t.Fatalf("write contract: %v", err)
			}

			err := GeneratePrometheusRules(GenerateOptions{
				ContractPath: contractPath,
				OutputPath:   outputPath,
				SourcePrefix: sourcePrefix,
			})
			if err != nil {
				t.Fatalf("GeneratePrometheusRules returned error: %v", err)
			}

			content, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatalf("read output: %v", err)
			}
			if !strings.Contains(string(content), "expr: sum by ("+clusterGrouping()+") ("+sourcePrefix+"_core_active)") {
				t.Fatalf("generated rules do not use supported prefix %q", sourcePrefix)
			}
		})
	}
}

func TestGeneratePrometheusRulesRejectsUnsupportedSourcePrefix(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "contract.yaml")
	outputPath := filepath.Join(dir, "rules.yaml")
	if err := os.WriteFile(contractPath, []byte(ruleContract()), 0o644); err != nil {
		t.Fatalf("write contract: %v", err)
	}

	err := GeneratePrometheusRules(GenerateOptions{
		ContractPath: contractPath,
		OutputPath:   outputPath,
		SourcePrefix: "bao",
	})
	if err == nil {
		t.Fatal("expected unsupported source prefix to fail")
	}
	for _, fragment := range []string{`metric source prefix "bao"`, "metricPrefixes.supported"} {
		if !strings.Contains(err.Error(), fragment) {
			t.Fatalf("error = %q, want text %q", err, fragment)
		}
	}
	if _, statErr := os.Stat(outputPath); !os.IsNotExist(statErr) {
		t.Fatalf("output was written for unsupported source prefix: %v", statErr)
	}
}

func TestValidatePromQLRejectsInvalidExpression(t *testing.T) {
	document := prometheusRule{
		Spec: prometheusRuleSpec{
			Groups: []prometheusRuleGroup{
				{
					Name: "test",
					Rules: []prometheusRuleItem{
						{Record: "openbao:invalid", Expr: "sum("},
					},
				},
			},
		},
	}

	err := validatePromQL(document)
	if err == nil {
		t.Fatal("expected invalid PromQL to fail")
	}
	if !strings.Contains(err.Error(), "openbao:invalid") {
		t.Fatalf("error does not include rule name: %v", err)
	}
}

func TestRequiredScrapeAlertUsesExactAbsenceFallback(t *testing.T) {
	document := loadGeneratedAlertDocument(t, "critical.yaml")
	expression := alertExpression(t, document, "OpenBaoUnreachable")
	expectedMatchers := map[string]matcherExpectation{
		"job": {value: "openbao", matcherType: promlabels.MatchEqual},
	}
	if !hasFunctionSelectorUnderBinaryOp(expression, "absent", "up", expectedMatchers, parser.LOR) {
		t.Fatalf("OpenBaoUnreachable has no exact absent(up) fallback under OR: %s", expression)
	}
	if hasSelectorMatcherType(expression, "up", "job", promlabels.MatchRegexp) {
		t.Fatalf("OpenBaoUnreachable uses a regular-expression job matcher: %s", expression)
	}
}

func TestCoreActiveSignalMissingUsesHealthyTargetInventory(t *testing.T) {
	document := loadGeneratedAlertDocument(t, "critical.yaml")
	expression := alertExpression(t, document, "OpenBaoCoreActiveSignalMissing")
	expectedMatchers := map[string]matcherExpectation{
		"job": {value: "openbao", matcherType: promlabels.MatchEqual},
	}
	if !hasSelectorUnderUnless(expression, "up", expectedMatchers) {
		t.Fatalf("OpenBaoCoreActiveSignalMissing has no exact healthy target inventory under UNLESS: %s", expression)
	}
	if !hasSelectorUnderUnless(expression, "openbao:core_active:sum", nil) {
		t.Fatalf("OpenBaoCoreActiveSignalMissing has no normalized core_active selector under UNLESS: %s", expression)
	}
}

func TestOptionalSignalMissingAlertsUseExpectationGate(t *testing.T) {
	tests := []struct {
		contractFile   string
		alertID        string
		signal         string
		optionalMetric string
	}{
		{
			contractFile:   "warning.yaml",
			alertID:        "OpenBaoKubernetesPodSignalMissing",
			signal:         "kubernetes_pods",
			optionalMetric: "kube_pod_container_status_ready",
		},
		{
			contractFile:   "critical.yaml",
			alertID:        "OpenBaoAuditArchiveSignalMissing",
			signal:         "audit_archive",
			optionalMetric: "openbao_audit_archive_enabled",
		},
		{
			contractFile:   "warning.yaml",
			alertID:        "OpenBaoSyntheticProbeSignalMissing",
			signal:         "synthetic_probe",
			optionalMetric: "probe_success",
		},
		{
			contractFile:   "warning.yaml",
			alertID:        "OpenBaoLogCollectorSignalMissing",
			signal:         "log_collector",
			optionalMetric: "up",
		},
	}

	for _, test := range tests {
		t.Run(test.alertID, func(t *testing.T) {
			document := loadGeneratedAlertDocument(t, test.contractFile)
			expression := alertExpression(t, document, test.alertID)
			expectedMatchers := map[string]matcherExpectation{
				"signal": {value: test.signal, matcherType: promlabels.MatchEqual},
			}
			if !hasSelectorUnderUnless(expression, "openbao_observability_signal_expected", expectedMatchers) {
				t.Fatalf("%s has no expectation selector under UNLESS: %s", test.alertID, expression)
			}
			if !hasSelectorUnderUnless(expression, test.optionalMetric, nil) {
				t.Fatalf("%s has no observed signal selector under UNLESS: %s", test.alertID, expression)
			}
		})
	}
}

func TestValueAlertsDoNotUseOptionalSignalAbsenceFallbacks(t *testing.T) {
	tests := []struct {
		contractFile string
		alertID      string
	}{
		{contractFile: "critical.yaml", alertID: "OpenBaoNoActiveNode"},
		{contractFile: "critical.yaml", alertID: "OpenBaoAllPodsUnavailable"},
		{contractFile: "critical.yaml", alertID: "OpenBaoAuditArchiveDegraded"},
		{contractFile: "warning.yaml", alertID: "OpenBaoSyntheticProbeFailing"},
		{contractFile: "warning.yaml", alertID: "OpenBaoAvailabilityFastBurn"},
		{contractFile: "warning.yaml", alertID: "OpenBaoAvailabilitySlowBurn"},
		{contractFile: "warning.yaml", alertID: "OpenBaoSyntheticProbeLatencyElevated"},
		{contractFile: "warning.yaml", alertID: "OpenBaoLogCollectorTargetDown"},
	}
	for _, test := range tests {
		t.Run(test.alertID, func(t *testing.T) {
			document := loadGeneratedAlertDocument(t, test.contractFile)
			expression := alertExpression(t, document, test.alertID)
			if hasFunctionCall(expression, "absent") {
				t.Fatalf("%s uses absent() in a value alert: %s", test.alertID, expression)
			}
		})
	}
}

func loadGeneratedAlertDocument(t *testing.T, contractFile string) prometheusRule {
	t.Helper()
	contractPath := filepath.Join("..", "..", "contracts", "alerts", contractFile)
	contract, err := contracts.LoadAlertContract(contractPath)
	if err != nil {
		t.Fatalf("load alert contract: %v", err)
	}
	if err := contract.ValidateExpressions(contract.DefaultSourcePrefix()); err != nil {
		t.Fatalf("validate contract expressions: %v", err)
	}

	document := buildAlertPrometheusRule(*contract, contract.DefaultSourcePrefix(), "test-alerts")
	if err := validatePromQL(document); err != nil {
		t.Fatalf("validate generated PromQL: %v", err)
	}
	return document
}

func alertExpression(t *testing.T, document prometheusRule, alertID string) string {
	t.Helper()
	for _, group := range document.Spec.Groups {
		for _, rule := range group.Rules {
			if rule.Alert == alertID {
				return rule.Expr
			}
		}
	}
	t.Fatalf("alert %s was not generated", alertID)
	return ""
}

type matcherExpectation struct {
	value       string
	matcherType promlabels.MatchType
}

func hasFunctionSelectorUnderBinaryOp(
	expression, function, metric string,
	expectedMatchers map[string]matcherExpectation,
	op parser.ItemType,
) bool {
	promQLParser := parser.NewParser(parser.Options{})
	parsed, err := promQLParser.ParseExpr(expression)
	if err != nil {
		return false
	}

	found := false
	parser.Inspect(parsed, func(node parser.Node, path []parser.Node) error {
		call, ok := node.(*parser.Call)
		if !ok || call.Func.Name != function || len(call.Args) != 1 || !hasBinaryOpAncestor(path, op) {
			return nil
		}

		selector, ok := call.Args[0].(*parser.VectorSelector)
		if !ok || selector.Name != metric || !hasExpectedMatchers(selector, expectedMatchers) {
			return nil
		}
		found = true
		return nil
	})
	return found
}

func hasFunctionCall(expression, function string) bool {
	promQLParser := parser.NewParser(parser.Options{})
	parsed, err := promQLParser.ParseExpr(expression)
	if err != nil {
		return false
	}

	found := false
	parser.Inspect(parsed, func(node parser.Node, _ []parser.Node) error {
		call, ok := node.(*parser.Call)
		if ok && call.Func.Name == function {
			found = true
		}
		return nil
	})
	return found
}

func hasSelectorUnderUnless(
	expression, metric string,
	expectedMatchers map[string]matcherExpectation,
) bool {
	promQLParser := parser.NewParser(parser.Options{})
	parsed, err := promQLParser.ParseExpr(expression)
	if err != nil {
		return false
	}

	found := false
	parser.Inspect(parsed, func(node parser.Node, path []parser.Node) error {
		selector, ok := node.(*parser.VectorSelector)
		if ok && selector.Name == metric &&
			hasExpectedMatchers(selector, expectedMatchers) &&
			hasBinaryOpAncestor(path, parser.LUNLESS) {
			found = true
		}
		return nil
	})
	return found
}

func hasSelectorMatcherType(expression, metric, matcherName string, matcherType promlabels.MatchType) bool {
	promQLParser := parser.NewParser(parser.Options{})
	parsed, err := promQLParser.ParseExpr(expression)
	if err != nil {
		return false
	}

	found := false
	parser.Inspect(parsed, func(node parser.Node, _ []parser.Node) error {
		selector, ok := node.(*parser.VectorSelector)
		if !ok || selector.Name != metric {
			return nil
		}
		for _, matcher := range selector.LabelMatchers {
			if matcher.Name == matcherName && matcher.Type == matcherType {
				found = true
			}
		}
		return nil
	})
	return found
}

func hasBinaryOpAncestor(path []parser.Node, op parser.ItemType) bool {
	for _, node := range path {
		if binary, ok := node.(*parser.BinaryExpr); ok && binary.Op == op {
			return true
		}
	}
	return false
}

func hasExpectedMatchers(selector *parser.VectorSelector, expected map[string]matcherExpectation) bool {
	for name, expectation := range expected {
		found := false
		for _, matcher := range selector.LabelMatchers {
			if matcher.Name == name && matcher.Value == expectation.value && matcher.Type == expectation.matcherType {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

func TestRecordingRulesUseNormalizedIdentityGrouping(t *testing.T) {
	document := buildPrometheusRule(contracts.MetricContract{
		Normalization: contracts.Normalization{RecordingRulePrefix: "openbao"},
	}, "openbao")

	targetRecords := map[string]bool{
		"openbao:core_unsealed:min":              true,
		"openbao:core_in_flight_requests:max":    true,
		"openbao:autopilot_node_healthy:min":     true,
		"openbao:raft_storage_commit_index:max":  true,
		"openbao:raft_storage_applied_index:max": true,
		"openbao:raft_storage_apply_gap:max":     true,
		"openbao:raft_storage_fsm_pending:max":   true,
		"openbao:runtime_num_goroutines:max":     true,
		"openbao:runtime_alloc_bytes:max":        true,
		"openbao:runtime_heap_objects:max":       true,
		"openbao:runtime_sys_bytes:max":          true,
		"openbao:runtime_total_gc_pause_ns:max":  true,
		"openbao:runtime_total_gc_runs:max":      true,
	}

	seenTargets := map[string]bool{}
	for _, group := range document.Spec.Groups {
		for _, rule := range group.Rules {
			if !strings.Contains(rule.Expr, clusterIdentityGrouping) {
				t.Errorf("rule %s does not preserve cluster identity: %s", rule.Record, rule.Expr)
			}

			_, isTargetRule := targetRecords[rule.Record]
			hasTargetIdentity := strings.Contains(rule.Expr, targetIdentityGrouping)
			if isTargetRule != hasTargetIdentity {
				t.Errorf("rule %s target grouping = %t, want %t: %s", rule.Record, hasTargetIdentity, isTargetRule, rule.Expr)
			}
			if isTargetRule {
				seenTargets[rule.Record] = true
			}
		}
	}

	for record := range targetRecords {
		if !seenTargets[record] {
			t.Errorf("target rule %s was not generated", record)
		}
	}
}

func TestRecordingRuleExpressionsPreserveSignalIdentity(t *testing.T) {
	document := buildPrometheusRule(contracts.MetricContract{
		Normalization: contracts.Normalization{RecordingRulePrefix: "openbao"},
	}, "openbao")

	allNodeA0 := signalLabels("cluster-a", "root", "all_nodes", "a-0", "10.0.0.1:8200")
	allNodeA1 := signalLabels("cluster-a", "root", "all_nodes", "a-1", "10.0.0.2:8200")
	activeA0 := signalLabels("cluster-a", "root", "active", "a-0", "10.0.0.1:8200")
	allNodeB0 := signalLabels("cluster-b", "root", "all_nodes", "b-0", "10.0.1.1:8200")
	allNodeB1 := signalLabels("cluster-b", "root", "all_nodes", "b-1", "10.0.1.2:8200")

	assertAggregateResults(t, recordingExpression(t, document, "openbao:core_active:sum"), []recordingSample{
		{labels: allNodeA0, value: 1},
		{labels: allNodeA1, value: 0},
		{labels: activeA0, value: 1},
		{labels: allNodeB0, value: 1},
		{labels: allNodeB1, value: 0},
	}, map[string]float64{
		clusterIdentityKey(allNodeA0): 1,
		clusterIdentityKey(activeA0):  1,
		clusterIdentityKey(allNodeB0): 1,
	})

	assertAggregateResults(t, recordingExpression(t, document, "openbao:core_unsealed:sum"), []recordingSample{
		{labels: allNodeA0, value: 1},
		{labels: allNodeA1, value: 0},
		{labels: activeA0, value: 1},
		{labels: allNodeB0, value: 1},
		{labels: allNodeB1, value: 1},
	}, map[string]float64{
		clusterIdentityKey(allNodeA0): 1,
		clusterIdentityKey(activeA0):  1,
		clusterIdentityKey(allNodeB0): 2,
	})

	assertAggregateResults(t, recordingExpression(t, document, "openbao:core_unsealed:min"), []recordingSample{
		{labels: allNodeA0, value: 1},
		{labels: allNodeA1, value: 0},
		{labels: activeA0, value: 1},
		{labels: allNodeB0, value: 1},
		{labels: allNodeB1, value: 1},
	}, map[string]float64{
		targetIdentityKey(allNodeA0): 1,
		targetIdentityKey(allNodeA1): 0,
		targetIdentityKey(activeA0):  1,
		targetIdentityKey(allNodeB0): 1,
		targetIdentityKey(allNodeB1): 1,
	})

	rootA := signalLabels("cluster-a", "root", "active", "a-0", "10.0.0.1:8200")
	teamA := signalLabels("cluster-a", "team-a", "active", "a-0", "10.0.0.1:8200")
	paymentsA := signalLabels("cluster-a", "payments", "active", "a-0", "10.0.0.1:8200")
	teamB := signalLabels("cluster-b", "team-a", "active", "b-0", "10.0.1.1:8200")
	assertAggregateResults(t, recordingExpression(t, document, "openbao:token_count:max30m"), []recordingSample{
		{labels: rootA, value: 6},
		{labels: teamA, value: 2},
		{labels: paymentsA, value: 1},
		{labels: teamB, value: 8},
	}, map[string]float64{
		clusterIdentityKey(rootA):     6,
		clusterIdentityKey(teamA):     2,
		clusterIdentityKey(paymentsA): 1,
		clusterIdentityKey(teamB):     8,
	})

	assertAggregateResults(t, recordingExpression(t, document, "openbao:runtime_heap_objects:max"), []recordingSample{
		{labels: allNodeA0, value: 100},
		{labels: allNodeA1, value: 200},
	}, map[string]float64{
		targetIdentityKey(allNodeA0): 100,
		targetIdentityKey(allNodeA1): 200,
	})
}

type recordingSample struct {
	labels map[string]string
	value  float64
}

func assertAggregateResults(t *testing.T, expression string, samples []recordingSample, want map[string]float64) {
	t.Helper()
	promQLParser := parser.NewParser(parser.Options{})
	parsed, err := promQLParser.ParseExpr(expression)
	if err != nil {
		t.Fatalf("parse PromQL expression %q: %v", expression, err)
	}
	aggregate, ok := parsed.(*parser.AggregateExpr)
	if !ok || aggregate.Without {
		t.Fatalf("expression is not a by-aggregate: %s", expression)
	}

	got := map[string]float64{}
	for _, sample := range samples {
		key := identityKey(aggregate.Grouping, sample.labels)
		value, exists := got[key]
		if !exists {
			got[key] = sample.value
			continue
		}
		switch aggregate.Op {
		case parser.SUM:
			got[key] = value + sample.value
		case parser.MIN:
			got[key] = min(value, sample.value)
		case parser.MAX:
			got[key] = max(value, sample.value)
		default:
			t.Fatalf("unsupported aggregate operation %s in %s", aggregate.Op, expression)
		}
	}

	if len(got) != len(want) {
		t.Fatalf("aggregate result count = %d, want %d: got %v, want %v", len(got), len(want), got, want)
	}
	for key, wantValue := range want {
		if gotValue, ok := got[key]; !ok || gotValue != wantValue {
			t.Errorf("aggregate result %q = %v, want %v", key, gotValue, wantValue)
		}
	}
}

func signalLabels(cluster, openbaoNamespace, scrapeProfile, pod, instance string) map[string]string {
	return map[string]string{
		"cluster":              cluster,
		"kubernetes_namespace": "secrets",
		"openbao_namespace":    openbaoNamespace,
		"scrape_profile":       scrapeProfile,
		"pod":                  pod,
		"instance":             instance,
	}
}

func clusterIdentityKey(labels map[string]string) string {
	return identityKey(strings.Split(clusterIdentityGrouping, ", "), labels)
}

func targetIdentityKey(labels map[string]string) string {
	return identityKey(strings.Split(targetIdentityGrouping, ", "), labels)
}

func identityKey(grouping []string, labels map[string]string) string {
	parts := make([]string, 0, len(grouping))
	for _, name := range grouping {
		parts = append(parts, name+"="+labels[name])
	}
	return strings.Join(parts, "|")
}

func recordingExpression(t *testing.T, document prometheusRule, record string) string {
	t.Helper()
	for _, group := range document.Spec.Groups {
		for _, rule := range group.Rules {
			if rule.Record == record {
				return rule.Expr
			}
		}
	}
	t.Fatalf("recording rule %s was not generated", record)
	return ""
}

func TestGenerateAlertRules(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "alerts.yaml")
	prometheusOutputPath := filepath.Join(dir, "prometheus-alerts.yaml")
	prometheusRuleFilePath := filepath.Join(dir, "prometheus-alert-rules.yaml")
	lokiOutputPath := filepath.Join(dir, "loki-alerts.yaml")

	if err := os.WriteFile(contractPath, []byte(alertContract()), 0o644); err != nil {
		t.Fatalf("write alert contract: %v", err)
	}

	err := GenerateAlertRules(GenerateAlertOptions{
		ContractPath:           contractPath,
		PrometheusOutputPath:   prometheusOutputPath,
		PrometheusRuleFilePath: prometheusRuleFilePath,
		LokiOutputPath:         lokiOutputPath,
		SourcePrefix:           "openbao",
	})
	if err != nil {
		t.Fatalf("GenerateAlertRules returned error: %v", err)
	}

	prometheusContent, err := os.ReadFile(prometheusOutputPath)
	if err != nil {
		t.Fatalf("read Prometheus output: %v", err)
	}
	prometheusText := string(prometheusContent)
	for _, fragment := range []string{
		"kind: PrometheusRule",
		"alert: OpenBaoNoActiveNode",
		"expr: openbao:core_active:sum == 0",
		"alert: OpenBaoMultipleActiveNodes",
		"expr: openbao:core_active:sum > 1",
		"alert: OpenBaoAutopilotFailureToleranceLost",
		"expr: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1",
		"component: raft",
		"alert: OpenBaoAuditResponseFailures",
		"expr: sum(increase(openbao_audit_log_response_failure[5m])) > 0",
		"runbook_url: https://github.com/dc-tec/openbao-observability/blob/main/docs/runbooks/no-active-openbao-leader.md",
	} {
		if !strings.Contains(prometheusText, fragment) {
			t.Fatalf("Prometheus alerts missing %q:\n%s", fragment, prometheusText)
		}
	}

	prometheusRuleFileContent, err := os.ReadFile(prometheusRuleFilePath)
	if err != nil {
		t.Fatalf("read Prometheus alert rule file: %v", err)
	}
	prometheusRuleFileText := string(prometheusRuleFileContent)
	for _, fragment := range []string{
		"groups:",
		"name: openbao.alerts",
		"alert: OpenBaoNoActiveNode",
		"expr: openbao:core_active:sum == 0",
		"alert: OpenBaoMultipleActiveNodes",
		"expr: openbao:core_active:sum > 1",
		"alert: OpenBaoAutopilotFailureToleranceLost",
		"expr: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1",
		"alert: OpenBaoAuditResponseFailures",
		"expr: sum(increase(openbao_audit_log_response_failure[5m])) > 0",
	} {
		if !strings.Contains(prometheusRuleFileText, fragment) {
			t.Fatalf("Prometheus alert rule file missing %q:\n%s", fragment, prometheusRuleFileText)
		}
	}
	if strings.Contains(prometheusRuleFileText, "kind: PrometheusRule") {
		t.Fatalf("native Prometheus alert rule file contains PrometheusRule wrapper:\n%s", prometheusRuleFileText)
	}

	lokiContent, err := os.ReadFile(lokiOutputPath)
	if err != nil {
		t.Fatalf("read Loki output: %v", err)
	}
	lokiText := string(lokiContent)
	for _, fragment := range []string{
		"kind: LokiAlertRules",
		"alert: OpenBaoAuditCanaryMissing",
		"expr: absent_over_time({log_stream=\"openbao.audit\"} | json request_path=\"request.path\" | " +
			"request_path=\"secret/data/observability/audit-canary\" [15m])",
	} {
		if !strings.Contains(lokiText, fragment) {
			t.Fatalf("Loki alerts missing %q:\n%s", fragment, lokiText)
		}
	}
}

func TestRunbookURLPreservesExternalURLs(t *testing.T) {
	const externalRunbook = "https://example.com/runbooks/openbao"
	if got := runbookURL(externalRunbook); got != externalRunbook {
		t.Fatalf("runbookURL() = %q, want %q", got, externalRunbook)
	}
}

func TestBuildPrometheusRuleUsesDefaultRecordPrefix(t *testing.T) {
	document := buildPrometheusRule(contracts.MetricContract{
		Normalization: contracts.Normalization{RecordingRulePrefix: "openbao"},
	}, "vault")

	if got := document.Spec.Groups[0].Rules[0].Record; got != "openbao:core_active:sum" {
		t.Fatalf("record name = %q", got)
	}
}

func ruleContract() string {
	return `version: v0.1
maturity:
  lifecycle: draft
  evidence:
    - documented
    - fixture-validated
    - generated-validated
openbaoVersion: "2.6.0"
metricPrefixes:
  supported:
    - vault
    - openbao
  default: vault
normalization:
  recordingRulePrefix: openbao
fixtures:
  required: []
metrics:
  - id: core_active
    prometheusName: ${p}_core_active
    required: true
`
}

func alertContract() string {
	return `version: v0.1
maturity:
  lifecycle: draft
  evidence:
    - documented
    - generated-validated
metricPrefixVariable: ${p}
sourcePrefix: vault
alerts:
  - id: OpenBaoNoActiveNode
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: openbao:core_active:sum == 0
    summary: OpenBao has no active node
    description: No active OpenBao node is visible to Prometheus.
    runbook: docs/runbooks/no-active-openbao-leader.md
  - id: OpenBaoMultipleActiveNodes
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: openbao:core_active:sum > 1
    summary: OpenBao has multiple active nodes
    description: More than one active OpenBao node is visible to Prometheus.
    runbook: docs/runbooks/multiple-active-nodes.md
  - id: OpenBaoAutopilotFailureToleranceLost
    type: prometheus
    severity: critical
    signal: metrics
    for: 2m
    expression: openbao:raft_peers:max >= 3 and openbao:autopilot_failure_tolerance:max < 1
    summary: OpenBao Autopilot has no tolerated voter failure
    description: >-
      OpenBao Autopilot reports that the Raft cluster cannot lose a voter while maintaining the configured HA baseline.
    runbook: docs/runbooks/raft-autopilot-health.md
    labels:
      component: raft
      subsystem: autopilot
  - id: OpenBaoAuditResponseFailures
    type: prometheus
    severity: critical
    signal: metrics
    for: 0m
    expression: sum(increase(${p}_audit_log_response_failure[5m])) > 0
    summary: OpenBao audit response logging failed
    description: OpenBao reported at least one audit response logging failure.
    runbook: docs/runbooks/audit-request-response-failures.md
  - id: OpenBaoAuditCanaryMissing
    type: loki
    severity: critical
    signal: loki
    for: 15m
    expression: >-
      absent_over_time({log_stream="openbao.audit"} | json request_path="request.path" |
      request_path="secret/data/observability/audit-canary" [15m])
    summary: OpenBao audit canary is missing
    description: Loki has not received the expected OpenBao audit canary request for the alert window.
    runbook: docs/runbooks/audit-canary-missing.md
`
}
