package rules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dc-tec/openbao-observability/internal/contracts"
)

func TestGeneratePrometheusRules(t *testing.T) {
	dir := t.TempDir()
	contractPath := filepath.Join(dir, "contract.yaml")
	outputPath := filepath.Join(dir, "rules.yaml")

	if err := os.WriteFile(contractPath, []byte(ruleContract()), 0o644); err != nil {
		t.Fatalf("write contract: %v", err)
	}

	err := GeneratePrometheusRules(GenerateOptions{
		ContractPath: contractPath,
		OutputPath:   outputPath,
		SourcePrefix: "openbao",
	})
	if err != nil {
		t.Fatalf("GeneratePrometheusRules returned error: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	text := string(content)

	required := []string{
		"# Code generated by openbao-observability; DO NOT EDIT.",
		"record: openbao:core_active:sum",
		"expr: sum(openbao_core_active)",
		"expr: sum(openbao_core_unsealed{cluster!=\"\"})",
		"source_prefix: openbao",
	}
	for _, fragment := range required {
		if !strings.Contains(text, fragment) {
			t.Fatalf("generated rules missing %q:\n%s", fragment, text)
		}
	}
}

func TestValidatePromQLRejectsInvalidExpression(t *testing.T) {
	document := prometheusRule{
		Spec: prometheusRuleSpec{
			Groups: []prometheusRuleGroup{
				{
					Name: "test",
					Rules: []recordingRule{
						{Record: "openbao:invalid", Expr: "sum("},
					},
				},
			},
		},
	}

	err := validatePromQL(document)
	if err == nil {
		t.Fatal("expected invalid PromQL to fail")
	}
	if !strings.Contains(err.Error(), "openbao:invalid") {
		t.Fatalf("error does not include rule name: %v", err)
	}
}

func TestBuildPrometheusRuleUsesDefaultRecordPrefix(t *testing.T) {
	document := buildPrometheusRule(contracts.MetricContract{
		Normalization: contracts.Normalization{RecordingRulePrefix: "openbao"},
	}, "vault")

	if got := document.Spec.Groups[0].Rules[0].Record; got != "openbao:core_active:sum" {
		t.Fatalf("record name = %q", got)
	}
}

func ruleContract() string {
	return `version: v0.1
status: draft
openbaoVersion: "2.5.4"
metricPrefixes:
  supported:
    - vault
    - openbao
  default: vault
normalization:
  recordingRulePrefix: openbao
fixtures:
  required: []
metrics:
  - id: core_active
    prometheusName: ${p}_core_active
    required: true
`
}
